### ISSUE TITLE
sitemap.xml file?

### ISSUE THREAD

**Issue by tamdrashtri** [zwbetz-gh/cupper-hugo-theme#10]
Hi again @zwbetz-gh, I'm trying to configure SEO for my blog and I could not find the sitemap.xml file? Any idea to do SEO on this Hugo blog? Thank you so much for your help!

**Comment by zwbetz-gh** [comment]
This file is automatically generated by Hugo at the root of your `public` directory. If you wish to customize it, see https://gohugo.io/templates/sitemap-template/#hugo-s-sitemap-xml

Am closing this issue.
