### ISSUE TITLE
Unfixed navigation on dark mode toggle (Firefox)

### ISSUE THREAD

**Issue by pcsteppan** [zwbetz-gh/cupper-hugo-theme#11]
**Description**
When in dark mode, the navigation on the left no longer sticks as the user scrolls, it gets stuck at the top.

**To Reproduce**

1. Open demo in firefox on desktop
2. Toggle darkmode on
3. Scroll down to see unfixed nav

**Expected behavior**
The navigation, like in the light mode, should follow the user as they scroll up and down the page.

**System info**
 - OS: Windows
 - Firefox
 - Version 67.0.3 (64-bit)

**Screenshot**
![Screenshot_2019-06-22 Cupper](https://user-images.githubusercontent.com/5924940/59968433-8cb8bf80-94ff-11e9-9196-a6dd11535cf7.png)

**Comment by zwbetz-gh** [comment]
Thanks for the report. As you noted, I can only reproduce this in Firefox, with dark mode on. Am investigating.

**Comment by rignato** [comment]
Hello I have created a PR for this issue, please check it out. #22

**Comment by zwbetz-gh** [comment]
Fixed in https://github.com/zwbetz-gh/cupper-hugo-theme/pull/22 by @rignato
