### ISSUE TITLE
Menu from directory structure

### ISSUE THREAD

**Issue by vdot0x23** [zwbetz-gh/cupper-hugo-theme#13]
As far as i can tell, menu layout has to be explicitly declared in the config.(toml/yaml/json).

Some themes infer the menu layout from directory structure, which would be nice for cupper aswell :) 

>Hugo assumes that the same structure that works to organize your source content is used to organize the rendered site.

https://gohugo.io/content-management/organization/

**Comment by zwbetz-gh** [comment]
Hello @vdot0x23 - I have no plans to add this feature. If you really want it, make a PR and I will review.
