### ISSUE TITLE
Site render problem

### ISSUE THREAD

**Issue by donho** [zwbetz-gh/cupper-hugo-theme#15]
(It's rather a support request)

Everything go fine in local mode by using `hugo.exe server -D`.
However while I try to render the site by using only `hugo.exe`, the page (under `public` folder) display become a mess:
 
![image](https://user-images.githubusercontent.com/90293/64337769-4fcd7680-cfe0-11e9-894d-7cd0705b4a96.png)

http://notepad-minus-minus.esy.es/

Could you en-light me how I should render  cupper-hugo-theme ?
BTW my hugo version is `Hugo Static Site Generator v0.57.2/extended windows/amd64`.

`

**Comment by zwbetz-gh** [comment]
This is because browsing your site via hugo server is different than browsing it via local file system.

**Comment by donho** [comment]
@zwbetz-gh Thank you for your prompted reply.

> This is because browsing your site via hugo server is different than browsing it via local file 
system.

I didn't browse it on my local system. I generate the static site by using the command `hugo.exe` instead of `hugo.exe server -D`, then deploy all the content in "public" folder to my site via ftp:
http://notepad-minus-minus.esy.es/

**Comment by donho** [comment]
Oups, it's a PEBCAK - Thanks to your reply I realize I didn't set **baseURL** right in  `config.toml` file.
Thank you for your assistance!
