### ISSUE TITLE
Unicode display problem

### ISSUE THREAD

**Issue by donho** [zwbetz-gh/cupper-hugo-theme#16]
**Describe the bug**
When the content is in French, the word with accent, like prononcée

**To Reproduce**
Add a sentence "Cette phrase prononcée par Greta Thunberg" to any content.
On the browser will show "Cette phrase prononc�e par Greta Thunberg"

**Expected behavior**
Display "Cette phrase prononcée par Greta Thunberg"

**Desktop (please complete the following information):**
 - OS: Ubuntu & Windows 10
 - Browser Firefox / Chrome

**Comment by zwbetz-gh** [comment]
I cannot reproduce this issue. 

I've created a special character test post in https://github.com/zwbetz-gh/cupper-hugo-theme/commit/5c9b53e9a5fa6046120c7616d25da16b0a11ac45

See it live at https://cupper-hugo-theme.netlify.com/special-character-test/

**Comment by donho** [comment]
@zwbetz-gh 
It's so embarrassing... it's another PBCAK - the file is just not in Unicode.
Thank you for your help!
