### ISSUE TITLE
Cupper's figure shortcode masks Hugo's default figure shortcode

### ISSUE THREAD

**Issue by zwbetz-gh** [zwbetz-gh/cupper-hugo-theme#17]
The below was originally posted in https://github.com/zwbetz-gh/cupper-hugo-theme/issues/12 by [@Teebusch](https://github.com/Teebusch). I'm moving it to its own issue. 

---

It seems that Cupper's figure shortcode masks Hugo's default figure shortcode. The two are different enough that they are both useful in different situations:

Hugo's figure shortcode allows linking of images in /static and adding a link to a picture directly
Cupper's shortcode has image processing built in, which is very useful. However, it centers the figure horizontally and "forces" a caption (otherwise there will be a "Figure x" text under the figure.
I would suggest to rename Cupper's shortcode, so Hugo's can be accessed.

(correct me if I'm wrong. I am new to Hugo)

**Comment by zwbetz-gh** [comment]
I've renamed Cupper's shortcode to `figureCupper`. See https://github.com/zwbetz-gh/cupper-hugo-theme/commit/315fe6a8d9b31b527b47d6506ead7f0ee97799a9. Closing this.

**Comment by Teebusch** [comment]
That was fast!! Thank you so much!
