### ISSUE TITLE
About scroll bar in homepage.

### ISSUE THREAD

**Issue by gapplef** [zwbetz-gh/cupper-hugo-theme#18]
**Describe the bug**
The homepage will always need scroll to shown the footer, even when that is little content on the page, leave out a long range of space.
You can see this from the demo site. I don't know if this should consider a bug. But is it possible to make the homepage fit the screen and show all content.

**Comment by zwbetz-gh** [comment]
The scroll behavior is on purpose. If you want to change it, edit this CSS line:
https://github.com/zwbetz-gh/cupper-hugo-theme/blob/315fe6a8d9b31b527b47d6506ead7f0ee97799a9/assets/css/template-styles.css#L321

**Comment by gapplef** [comment]
@zwbetz-gh thanks for you help.

And I found the correct line should be modified is the following one, as a reference for any one may also want to change the default behaviour.
https://github.com/zwbetz-gh/cupper-hugo-theme/blob/315fe6a8d9b31b527b47d6506ead7f0ee97799a9/assets/css/template-styles.css#L550

**Comment by zwbetz-gh** [comment]
@gapplef good catch 👍
