### ISSUE TITLE
Syntax highlighting other languages than html

### ISSUE THREAD

**Issue by szd** [zwbetz-gh/cupper-hugo-theme#23]
Hi,

I see that cupper uses prismjs to syntax highlight code.
When I use the documentation example, it works (HTML):
\`\`\`html
But when I try with an other prismjs supported language, it doesn't works:
\`\`\`sql
My code stays non-colored.

How can I add more languages in the default installed prismjs ?

**Comment by zwbetz-gh** [comment]
Hi -- you can pick the languages you want from this builder 

https://prismjs.com/download.html#themes=prism&languages=markup+css+clike+javascript

Then copy the downloaded CSS and JS files to

https://github.com/zwbetz-gh/cupper-hugo-theme/blob/master/static/css/prism.css
https://github.com/zwbetz-gh/cupper-hugo-theme/blob/master/static/js/prism.js

**Comment by daijiang** [comment]
Hi, it seems that R code chunks in Rmd files are not highlighted. Any idea how to enable it? Thanks!

**Comment by zwbetz-gh** [comment]
> Hi, it seems that R code chunks in Rmd files are not highlighted. Any idea how to enable it? Thanks!

Hi @daijiang, since this issue is already resolved, would you open a new issue please?

Also, provide as much detail as possible, so that I can try to reproduce the new issue. Thanks.
