### ISSUE TITLE
New Chrome update breaks hugo/cupper site "skip to content" banner along the top

### ISSUE THREAD

**Issue by joelouthan** [zwbetz-gh/cupper-hugo-theme#24]
**Describe the bug**
Recent Chrome update (MacOS, Linux, etc.) now renders the site with "skip to content" black banner across the top

**To Reproduce**
1. Go to: https://theologic.us/
2. Click on: nothing
3. Scroll down to: it's on the main page

**Expected behavior**
Not to have a black banner that says "skip to content"

**Screenshots**
![image](https://user-images.githubusercontent.com/8844984/76862774-93752880-682c-11ea-894c-3d28f6ca6bf7.png)

**Desktop (please complete the following information):**
 - OS: Fedora 31 or MacOS 10.15.3
 - Browser: Chrome 
 - Version: 80.0.3987.132

**Comment by zwbetz-gh** [comment]
I cannot reproduce your issue

I've tested with Chrome Version 80.0.3987.149

I don't have a Mac to test with at the moment, but I've tested with Windows 10 and Ubuntu 18.04

**Comment by joelouthan** [comment]
I have no reason why I was so put off by this.

`grep -R "skip to content" *
themes/cupper/layouts/_default/baseof.html:    <a href="#main">skip to content</a>`

Just went into that file and deleted that line. Easy peasy.
