### ISSUE TITLE
'Tags', 'Publish date' and 'toc' in blog article doesn't work.

### ISSUE THREAD

**Issue by DDQ233** [zwbetz-gh/cupper-hugo-theme#25]
I very love this theme. Thank you. I find an issue that I can not handle it, so I have to ask you to help me solve this problem.

I used cupper theme and run the 'exampleSite' , then I find every blog article without 'Tags', 'Publish date' and 'toc' doesn't work.

For example : 

Your demo :

```text
🔢 This is title
Publish date: Sep 28, 2014
Tags: hugo theme command-line

Table of contents

Main body
```

My blog : 

```text
🔢 This is title

Main body
```

[Your demo result](https://themes.gohugo.io//theme/cupper-hugo-theme/creating-a-new-theme/)
[My blog result](https://ddq233.github.io/notes/cupper-typography/)

**Comment by zwbetz-gh** [comment]
The theme is expecting your blog posts to be under the `content/post` directory. I see you are using directory `content/notes` instead. That is fine. 

To fix it, you will need to rename the theme's layout directory from `layouts/post/` to `layouts/notes/`

**Comment by DDQ233** [comment]
I successfully fixed the issue. Thank you so much !

**Comment by bravegrape** [comment]
Also a big fan of this theme and this issue helped me fix my problem too 🎉  
Thank you both 🙌
