### ISSUE TITLE
Fonts not working on custom domain

### ISSUE THREAD

**Issue by matiasilva** [zwbetz-gh/cupper-hugo-theme#27]
**Describe the bug**
The heading font does not carry over on a custom domain

**To Reproduce**
1. Go to [this link](https://coderdojo-lx.pt)

**Expected behavior**
The Cupper font would load.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox, Chrome
 - Version: most recent

**Comment by matiasilva** [comment]
Nevermind...

**Comment by matiasilva** [comment]
As soon as I add a CNAME, fonts no longer work..

**Comment by zwbetz-gh** [comment]
Open chrome devtools, do you see any errors?

**Comment by matiasilva** [comment]
Yes, CORS errors..

**Comment by zwbetz-gh** [comment]
I cannot help you with a CORS error, as this is not a cupper theme issue.
You must fix that yourself via your web server config. Closing this issue.
