### ISSUE TITLE
Couldn't be published to github

### ISSUE THREAD

**Issue by jinbeomhong** [zwbetz-gh/cupper-hugo-theme#3]
**Describe the bug**

I followed instructions to install cupper-hugo-theme from [here](https://themes.gohugo.io/cupper-hugo-theme/). After that, i followed instructions to publish static site to github from [here](https://gohugo.io/hosting-and-deployment/hosting-on-github/#step-by-step-instructions). But, an error comes up from github repository setting page:

```
Your site is having problems building: The tag image on line 129 in themes/cupper-hugo-theme/exampleSite/content/post/migrate-from-jekyll.md is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error/.
```

**To Reproduce**
1. Follow instructions from https://gohugo.io/getting-started/quick-start/
    + You should replace a theme with cupper-hugo-theme.
2. Follow instructions from https://gohugo.io/hosting-and-deployment/hosting-on-github/ to host  website on github
3. Go to setting page of repository.

```bash
$ ls
archetypes  config.toml  content  data  deploy.sh  layouts  public  resources  static  themes

$ ls public/
android-chrome-192x192.png  apple-touch-icon.png  categories  favicon-16x16.png  favicon-96x96.png  images      index.xml  mstile-150x150.png     site.webmanifest  tags
android-chrome-512x512.png  browserconfig.xml     css         favicon-32x32.png  favicon.ico        index.html  js         safari-pinned-tab.svg  sitemap.xml
```

**Screenshots**

<img width="669" alt="2019-02-22 11 04 46" src="https://user-images.githubusercontent.com/32840866/53247301-58bac280-36f6-11e9-9af4-64ae8df36e64.png">

**Desktop (please complete the following information):**
 - OS : macOS
 - Browser : chrome

**Comment by zwbetz-gh** [comment]
Hi @jinbeomhong. The following error you gave:

> Your site is having problems building: The tag image on line 129 in themes/cupper-hugo-theme/exampleSite/content/post/migrate-from-jekyll.md is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error/.

Has nothing to do with the Cupper theme, but is an issue with your GitHub Pages configuration.

I have never used GitHub Pages, but from reading that error message, "Liquid tag" is a Jekyll thing, so for some reason your site is being seen as a Jekyll site instead of a Hugo site. I'd recommend reading the GitHub Pages [docs](https://help.github.com/en/categories/github-pages-basics) to troubleshoot the error.

Am closing this issue.

**Comment by zwbetz-gh** [comment]
Also, I'd recommend posting your issue to the Hugo forum https://discourse.gohugo.io/ as that is the more appropriate place to troubleshoot this issue. If you share your site code, folks will be able to help you better.
