### ISSUE TITLE
Markup in expandable, no longer rendering

### ISSUE THREAD

**Issue by kamaradski** [zwbetz-gh/cupper-hugo-theme#30]
**Describe the bug**
As of this morning markup inside the expandable tags is no longer rendering correctly. This is observable on both the demo-site as well as my local hosted site.

**To Reproduce**
Steps to reproduce the behaviour:  
- open the demo site: https://themes.gohugo.io//theme/cupper-hugo-theme/cupper-shortcodes/#expandable  
- expand the demo-expandable  
- notice that the link in markup is no longer rendered as such  

**Tested:**
- Tried both Chrome Version 83.0.4103.61 (Official Build) (64-bit) & Firefox 76.0.1 (64-bit)  
- Tried different markup locally:  
    - double-empty-space new lines (result in no new-line with visible double-space)  
    - tables (result in wall of text and pipe-symbols)  

**Expected behaviour**
The markup inside these expandable tags to render as usual

**Screenshots**
Chrome:  
![image](https://user-images.githubusercontent.com/15661489/83513337-ebd5d100-a4d1-11ea-8854-b20aaa0d9117.png)

Firefox:  
![image](https://user-images.githubusercontent.com/15661489/83513432-12940780-a4d2-11ea-8f50-51415707a723.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.4 (19E287)
 - Browser: Chrome Version 83.0.4103.61 (Official Build) (64-bit) & Firefox 76.0.1 (64-bit)

**Smartphone (please complete the following information):**
- did not try

**Comment by zwbetz-gh** [comment]
Good catch. This has been fixed in https://github.com/zwbetz-gh/cupper-hugo-theme/commit/eba92554484b086843e16bfeed9ceed839ab00df

The official hugo themes demo may take a few days to update, so in the meantime, verify the change here https://cupper-hugo-theme.netlify.app/cupper-shortcodes/#expandable

**Comment by kamaradski** [comment]
confirmed, fix worked on my own site, as soon as I re-triggered my ci/cd pipeline :) 
thanks!
