### ISSUE TITLE
Ability to set darkTheme as default theme

### ISSUE THREAD

**Issue by kamaradski** [zwbetz-gh/cupper-hugo-theme#31]
**Is your feature request related to a problem? Please describe.**
I would like my visitors to be presented with the `darkTheme`as default, and allow them to switch to the whiteTheme if they prefer this instead. default behaviour is currently to first show the whiteTheme.

**Describe the solution you'd like**
this could be a config setting or something in the header partial template?

**Describe alternatives you've considered**
i tried to understand the dom-scripts.js, but am totally lost when it comes to js

**Additional context**
N/A

**Comment by zwbetz-gh** [comment]
I like the idea. It has been added in https://github.com/zwbetz-gh/cupper-hugo-theme/commit/1ca724981052ff0b3e7ed49a05fc0c6c16ced544
