### ISSUE TITLE
Menu not rendering

### ISSUE THREAD

**Issue by weeyin83** [zwbetz-gh/cupper-hugo-theme#32]
I am running hugo locally and when installing the cupper theme, I get no side bar menu listed. 

Is there something I need to explicitly call out or change?

**Comment by zwbetz-gh** [comment]
You will need to add menu config to your config file. For a sample, see 

https://github.com/zwbetz-gh/cupper-hugo-theme/blob/1ca724981052ff0b3e7ed49a05fc0c6c16ced544/exampleSite/config.yaml#L37-L53

**Comment by weeyin83** [comment]
Thanks @zwbetz-gh, I am using the examplesite config file, and I am not getting anything rendered down the left hand side. The menu isn't there.

**Comment by zwbetz-gh** [comment]
Share your repo if you can. Hard to troubleshoot this in the dark.

**Comment by weeyin83** [comment]
My repo is the basic Hugo install with the cupper theme, there isn't a lot there, I am using most of the example site files to start to figure out how things work. 

https://github.com/weeyin83/Hugo-workinprogress

**Comment by zwbetz-gh** [comment]
Found your issue :)

Your `config.toml` is overriding your `config.yaml`

So either delete your `config.toml` or rename it to something like `config.toml.bak`. Then re run `hugo server` and you should see your menu

**Comment by weeyin83** [comment]
Unfortunately without the toml file the site fails to build

INFO 2020/06/05 15:21:26 Using config file:
Building sites … INFO 2020/06/05 15:21:26 syncing static files to c:\Hugo\sites\workinprogress\
ERROR 2020/06/05 15:21:26 Failed to read Git log: fatal: not a git repository (or any of the parent directories): .git
Built in 101 ms
Error: Error building site: logged 1 error(s)

**Comment by zwbetz-gh** [comment]
It runs fine for me:

```
$ hugo server

                   | EN
-------------------+-----
  Pages            | 37
  Paginator pages  |  0
  Non-page files   |  0
  Static files     | 32
  Processed images |  0
  Aliases          |  0
  Sitemaps         |  1
  Cleaned          |  0

Built in 59 ms
Watching for changes in ~/development/playground/hugo/Hugo-workinprogress/{archetypes,content,themes}
Watching for config changes in ~/development/playground/hugo/Hugo-workinprogress/config.yaml
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

There may be another issue on your end.
