### ISSUE TITLE
'config.yaml' file encoding problem

### ISSUE THREAD

**Issue by DDQ233** [zwbetz-gh/cupper-hugo-theme#33]
**Describe the bug**
I used 'UTF-8' encoding to edit the 'config.yaml' file, the content was in Chinese, but after executing 'hugo' command on the console, the file encoding changed from 'UTF-8' to 'Windows1252', the content in Chinese was confused. However, the website content displayed normally.

Why does it happen ? I want to execute the 'hugo' command on the console without changing the encoding of the 'config.yaml' file.

---

before runing command:

```text
baseURL: https://ddq233.github.io/
languageCode: en-us
defaultContentLanguage: zh-cn
title: DDQ的笔记
theme: cupper
```

after runing command:

```text
baseURL: https://ddq233.github.io/
languageCode: en-us
defaultContentLanguage: zh-cn
title: DDQçš„ç¬”è®°
theme: cupper
```

**Comment by zwbetz-gh** [comment]
The behavior you are describing is not an issue with this theme. It is either an issue with hugo itself, or with your local environment. 

Try asking your question on the general hugo forums https://discourse.gohugo.io/

Closing this issue.
