### ISSUE TITLE
Code block background colors controlled by element.style and not css

### ISSUE THREAD

**Issue by joelouthan** [zwbetz-gh/cupper-hugo-theme#38]
**Describe the bug**
Trying to set the background of Code blocks but is getting overran by element.style in either light or dark mode

**To Reproduce**
1. Write a post
2. Using three ticks to start and three ticks to finish the code block
3. In Light mode, the code blocks are dark gray with dark font. In Dark mode, the code blocks are light grey with light font.

**Expected behavior**
I honestly don't care what color the blocks are. I just need it to be readable.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zwbetz-gh** [comment]
Markdown code blocks are working as expected, as long as you **specify the language**, and have the [settings configured](https://github.com/zwbetz-gh/cupper-hugo-theme/blob/10ae1fcf36919371eabf9a458015c5c25aba602a/exampleSite/config.yaml#L74-L82). For example:

## Light mode

<img width="1680" alt="Screen Shot 2020-06-20 at 2 35 10 PM" src="https://user-images.githubusercontent.com/37317628/85210204-8e2fea00-b303-11ea-9bd5-45e4eabb8db1.png">

## Dark mode

<img width="1672" alt="Screen Shot 2020-06-20 at 2 35 23 PM" src="https://user-images.githubusercontent.com/37317628/85210207-925c0780-b303-11ea-9d3d-32cb14aab40a.png">

**Comment by zwbetz-gh** [comment]
If you are trying to do custom syntax highlighting, other than what [chroma](https://gohugo.io/content-management/syntax-highlighting/) provides out of the box, then that is out of scope for a theme issue. It must be solved individually.
