### ISSUE TITLE
mysite\config.toml:1:1": unmarshal failed: Near line 0 (last key parsed ''): bare keys cannot contain ':'

### ISSUE THREAD

**Issue by kairoslab** [zwbetz-gh/cupper-hugo-theme#39]
I apologize if this is truly a naive oversight. 

I copied the config.yaml code to config.toml on Virtual Studio Code under my new hugo site;
 when I run hugo server I get this error

\config.toml:1:1": unmarshal failed: Near line 0 (last key parsed ''): bare keys cannot contain ':'

I'm working from Command Prompt as Administrator on Windows. 
The theme has been cloned to the site folder, which is on my Desktop. 
The Demo Site seems to run fine on my local server.  

Let me know if you need more information. 
I really appreciate any help, and the fact that you created such a great theme.

**Comment by zwbetz-gh** [comment]
You are getting that error because you are trying to use YAML syntax in a TOML file. 

I would recommend using the sample `config.yaml` file as-is, **or** converting the YAML syntax to TOML.

**Comment by kairoslab** [comment]
Thank you!
