### ISSUE TITLE
Umlaut characters broken in headlines on Firefox

### ISSUE THREAD

**Issue by yayachiken** [zwbetz-gh/cupper-hugo-theme#40]
**Describe the bug**
German Umlaut characters and Eszett (ÄÖÜäöüß) do not render in headline font in Firefox.

**To Reproduce**
1. Create a page with the Text "ÄAÖOÜUäaöoüoßss"
2. Open page in Chrome, text renders fine.
3. Open page in Firefox (version 78.0.2 on Linux), Umlaut characters render in a fallback font.

**Expected behavior**
Chrome and Firefox render the fonts the same, especially the special characters should fit in.

**Screenshots**

Example 1 from a real page (note the headlines):
![umlaut-error](https://user-images.githubusercontent.com/88805/87244101-6da70b80-c43b-11ea-9789-16d1417ca419.png)

Example 2 from fontdrop.info:
![umlaut-error2](https://user-images.githubusercontent.com/88805/87244099-6d0e7500-c43b-11ea-92a9-044bfd00f0eb.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser Firefox
 - Version 78.0.2

**Additional context**
I was also able to reproduce the behaviour by uploading the woff font to https://fontdrop.info/ and putting in the above mentioned text in the "Type yourself" field, maybe only the woff font is broken and woff2 works?

**Comment by zwbetz-gh** [comment]
I am not familiar when it comes to multilingual font support... so:

Do you think that Firefox itself has an issue, and this is why Chrome shows it fine?

Or, do you think that this theme has an issue, and Chrome is doing some silent error handling to show it fine?

**Comment by zwbetz-gh** [comment]
> I am not familiar when it comes to multilingual font support... so:
> 
> Do you think that Firefox itself has an issue, and this is why Chrome shows it fine?
> 
> Or, do you think that this theme has an issue, and Chrome is doing some silent error handling?

@yayachiken ?

**Comment by zwbetz-gh** [comment]
Closing this issue for reasons:
- Issue opener is unresponsive
- I do not plan to fix this, as I am not sure it is an actual bug

**Comment by yayachiken** [comment]
Sorry that I do not immediately respond within my own leisure time.

The root cause is as I said already: The fonts packaged with the theme are broken. Redownloading the Miriam Libre Bold font from Google helps, the font size gets increased by about 5 kB per file (woff/woff2) so that's a bit of a tradeoff for better i18n.

I would have filed a PR, but if you are that impatient, you will have to do that by yourself now. The information I gave should be well sufficient to fix this.

**Comment by zwbetz-gh** [comment]
You opened the issue 16 days ago. Keep in mind this is my leisure time as well. 

If I came off harsh, that is not my intent. If someone were to submit a PR for this, I would gladly review it.

**Comment by zwbetz-gh** [comment]
Fixed by @fkohrt in https://github.com/zwbetz-gh/cupper-hugo-theme/pull/43

Please verify @yayachiken

**Comment by yayachiken** [comment]
I have not tried out this specific commit, but it seems @fkhort implemented the fix I described (redownloading fonts) , so this should be alright.
