### ISSUE TITLE
Multi-line {{<cmd>}}

### ISSUE THREAD

**Issue by duncan-wither** [zwbetz-gh/cupper-hugo-theme#42]
**Is your feature request related to a problem? Please describe.**
When using the `cmd` tag for more than one line of code it concatinates the lines. 
The alternative is to have multiple `cmd` tags, however then you've seperate boxes (which I'd rather not have).

I've tried putting in `//`, multiple new lines and `<br>` but none of these work.

**Describe the solution you'd like**
It's be excellent if
```
{{< cmd >}}
One line
Two line
{{< cmd >}}
```
Would appear in the same black box similar to:
```
$ One Line
$ Two Line
```
But anything would be great.

**Describe alternatives you've considered**
using the default .md tabbing, or ``` but neither is as nice as the cmd tag.

**Additional context**
Any assistance would be really appreciated.

**Comment by zwbetz-gh** [comment]
I like the idea. Done in https://github.com/zwbetz-gh/cupper-hugo-theme/commit/72bb0d7e7e3e623e2f751f3a9375ca6df4ed210f

**Comment by zwbetz-gh** [comment]
See a sample usage at https://cupper-hugo-theme.netlify.app/cmd-test/

**Comment by duncan-wither** [comment]
Amazing, works perfectly. Thank you.
