### ISSUE TITLE
Setting dark mode by default makes website load in lightmode for a split second. 

### ISSUE THREAD

**Issue by ivnvitx** [zwbetz-gh/cupper-hugo-theme#44]
I really like dark mode, and I love the setting for making it a default, but it seems to me that the implementation lacks a bit in terms of results, as most times you can clearly tell it's loading the light colors and then it switches to dark mode.

**Comment by zwbetz-gh** [comment]
You must provide more detail for me to work with. Please close this issue and open a new one using the bug template, then fill it out accordingly with your env info.

**Comment by zwbetz-gh** [comment]
Closing this issue, and awaiting another issue to be opened with much more detail.
