### ISSUE TITLE
Add CustomJS

### ISSUE THREAD

**Issue by guyou** [zwbetz-gh/cupper-hugo-theme#46]
**Is your feature request related to a problem? Please describe.**
I wish to be able to add leaflet. But it requires bothe a CSS and a JS script.

**Describe the solution you'd like**
Having a CustomJS Site property (or section property) could made it easily adaptable.

**Comment by zwbetz-gh** [comment]
I like the idea. And this was already partially supported, via custom CSS. 

But now both custom CSS and JS files are supported, and better documented. 

See commit 9824fe3e2e0b54c7320df87effcfed1455989119

Closing this.
