### ISSUE TITLE
Table of Contents not working for non ASCII characters

### ISSUE THREAD

**Issue by andradei** [zwbetz-gh/cupper-hugo-theme#5]
**Describe the bug**
Table of Contents is rendered with `href` that won't point correctly to `h2`s in markdown content if characters like ã, ç, õ, é, etc. are used.

For example:

The markdown header

```
## Introdução
```

gets rendered with an `a href="#introduc-a-o"` but the table of contents points to `<a href="#introduc%25CC%25A7a%25CC%2583o">Introdução</a>`.

This has to do with the way the `href`s get generated in markdown and `partials/toc.html` being different.

While it works for ASCII characters, it doesn't for the rest.

**To Reproduce**
1. Create any `.md` post with `## Introdução`, for example
1. Turn on Table of Contents

**Expected behavior**
The escaped URL for _Nação_ be the same in the Table of Contents and the actual `h2`'s `a` tag, so that the links can be followed from the Table of Contents

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.3 (18D109)
 - Browser: Firefox
 - Version: 66.0b10 (64-bit)

**Comment by zwbetz-gh** [comment]
Thanks for opening this issue @andradei. It has been fixed in 35ccaa2.
