### ISSUE TITLE
Date translation

### ISSUE THREAD

**Issue by ellypsis** [zwbetz-gh/cupper-hugo-theme#51]
**Is your feature request related to a problem? Please describe.**
I'm trying to use [this method](https://gohugo.io/content-management/multilingual/#customize-dates) to translate months.

**Describe the solution you'd like**
How to incorporate this solution in the template?
Can I use a solution without modification on theme files? (update in mind)

**Describe alternatives you've considered**
Incorporate a translation method with i18n config for time-date translation, as Go doesn't support it yet

**Additional context**
I'm still a newbie in coding, but have some knowledge.
Thanks for helping me!

**Comment by zwbetz-gh** [comment]
Hi @ellypsis. You can do your date translation work by [overriding](https://zwbetz.com/override-a-hugo-theme/) this [template file](https://github.com/zwbetz-gh/cupper-hugo-theme/blob/master/layouts/post/single.html)

**Comment by ellypsis** [comment]
Thank you for your quick answer.
I didn't know (read enough...) I could do that!
I founded the right file to modify but didn't know how to do it. Finally made it works.
You did a really great work with this forked theme. Really like it :+1:

**Comment by zwbetz-gh** [comment]
Glad to hear you found a solution. And thank you for the kind words
