### ISSUE TITLE
Alt text for logo

### ISSUE THREAD

**Issue by tanyabouman** [zwbetz-gh/cupper-hugo-theme#52]
**Is your feature request related to a problem? Please describe.**
Alt text on the logo is an empty string.  Setting the alt text to something meaningful is necessary for accessibility.

**Describe the solution you'd like**
I found that it worked well to add a key in the config file called `logoAltText` and then replace the line that inserts the logo with:
```
 <img src="{{ "images/logo.svg" | relURL }}" alt="{{ .Site.Params.LogoAltText }}" >
```

**Describe alternatives you've considered**
Aria text already describes it as a logo, so that might be sufficient, but sometimes the logo has more details that might be helpful to include in alt text.

**Comment by zwbetz-gh** [comment]
I like the idea. This has been added in fa9968a3ed2ff11a41c36d76cf752f0aa1701e6a
