### ISSUE TITLE
Error whle using Cupper Theme

### ISSUE THREAD

**Issue by pm-bhatt** [zwbetz-gh/cupper-hugo-theme#54]
**Describe the bug**
Tried to use Cupper theme in Hugo site. It does not work

Gives below error : 

**_`themes/cupper-hugo-theme-master/layouts/partials/head.html:14:1": parse failed: template: partials/head.html:14: unclosed action`_**

**To Reproduce**
Just integrate into the new Hugo site without any changes and run the Hugo server, and you will see the error.

**Expected behavior**
Ideally, it should run with a basic cupper theme.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS - WSL

**Comment by zwbetz-gh** [comment]
Make sure you have the minimum hugo version (or higher) installed.

This is mentioned in the README. Currently it's 0.81.0

**Comment by zwbetz-gh** [comment]
Closing this.
