### ISSUE TITLE
syntax highlight for R code chunk in Rmd file

### ISSUE THREAD

**Issue by daijiang** [zwbetz-gh/cupper-hugo-theme#55]
Hi, it seems that R code chunks in Rmd files are not highlighted. Any idea how to enable it? Thanks!

To reproduce the issue, create a new site with this theme

```r
blogdown::new_site(theme = "zwbetz-gh/cupper-hugo-theme")
blogdown::serve_site()
```

Then, go to the Blog and click the `hello R markdown` post. The syntax highlighting does not work on the R code chunks.

**Comment by zwbetz-gh** [comment]
Hey @daijiang. So syntax highlighting in this theme is done via Prism. The `R` language is not included by default, but you can add it.

I've pushed some steps, see c2914816e1611e252986cae02da700b95a2ae652

**Comment by zwbetz-gh** [comment]
And, a link to the readme section https://github.com/zwbetz-gh/cupper-hugo-theme#syntax-highlighting

**Comment by zwbetz-gh** [comment]
Make sure when writing `R` snippets, you specify the language like:

````
```r
Lst <- list(name="Fred", wife="Mary", no.children=3, child.ages=c(4,7,9))
```
````

This is how you do it in markdown (`.md`) files. I am not sure if Rmd files are different?

**Comment by daijiang** [comment]
Hi thanks! I figured out that for .md files based on a previous issue. But it seems .Rmd files are different since the R code chinks are not highlighted after including R language in the css and js files. Can you take a look at it again? Really appreciate your help!

**Comment by zwbetz-gh** [comment]
Interesting. I'll have to play with `.Rmd` a bit and see.

**Comment by zwbetz-gh** [comment]
When you say `.Rmd` files, does that mean you're using Blogdown?

Regardless, try setting this [option](https://gohugo.io/getting-started/configuration-markup/) in your `config.yaml` file. It will disable Hugo's built-in syntax highlighting. (On the off change it's overriding Prism). 

```yaml
highlight:
  codeFences: false
```

**Comment by zwbetz-gh** [comment]
Any luck on your end?

**Comment by daijiang** [comment]
Nope, the code chunks in Rmd posts are still not highlighted...

**Comment by zwbetz-gh** [comment]
Hmm.

If you'd like me to investigate further, please share a sample R markdown
repo where I can reproduce the issue.

Also, keep in mind that I expect this theme to work on a normal site setup.

Whereas for an R markdown project, I'm unsure what "magic" is happening in
that framework, that may complicate things.

**Comment by daijiang** [comment]
Ok, thanks. I though this is the Rmd version of the cupper theme. I probably just did not pay attention. 

But anyway, here is the html generated by default:

```html
<pre class="r"><code>data(cars)
plot(cars$dist, cars$speed)</code></pre>
```

If I change it to the following, the highlighting will work. 

```html
<pre><code class="language-r">data(cars)
plot(cars$dist, cars$speed)</code></pre>
```

Here is the repo if you want to check it out. (`content/post`) Thanks!

**Comment by daijiang** [comment]
Ok, I just added some R code to replace `class="r"` with `class="language-r"` for all post html files. And it works.
So no worries. At least it is solved at my end.
Thanks for your help.

**Comment by zwbetz-gh** [comment]
Cool. Glad to hear it.

Now future R markdown users can refer back to this thread and hopefully
profit.

**Comment by daijiang** [comment]
Not sure what happened. But when I try to create a brand new site with this theme. I got the following error:

```
> blogdown::new_site(theme = "zwbetz-gh/cupper-hugo-theme")
― Creating your new site
| Installing the theme zwbetz-gh/cupper-hugo-theme from github.com
trying URL 'https://github.com/zwbetz-gh/cupper-hugo-theme/archive/master.tar.gz'
downloaded 7.1 MB

| Adding the sample post to /Users/dli30/Documents/test/content/post/2020-12-01-r-rmarkdown/index.en.Rmd
| Converting all metadata to the YAML format
Error: logged 1 error(s)
| Adding netlify.toml in case you want to deploy the site to Netlify
| Adding .Rprofile to set options() for blogdown
― The new site is ready
○ To start a local preview: use blogdown::serve_site(), or the RStudio add-in "Serve Site"
○ To stop a local preview: use blogdown::stop_server(), or restart your R session
► Want to serve and preview the site now? (y/n) y
Launching the server via the command:
  /Users/dli30/Library/Application Support/Hugo/0.85.0/hugo server --bind 127.0.0.1 -p 4321 --themesDir themes -t cupper-hugo-theme -D -F --navigateToChanged
Error: Error building site: logged 1 error(s)
```

**Comment by zwbetz-gh** [comment]
I don't see the actual logged error in that output.

But double check your hugo version. And make sure you have the minimum
version or higher, as mentioned in the theme readme.

**Comment by daijiang** [comment]
I have 0.85.0, which is higher than the minimal. My guess is that maybe some of recent commits caused this? I did not see the log info neither.

**Comment by zwbetz-gh** [comment]
Hard for me to debug without an error message, stack trace, or line number.

**Comment by daijiang** [comment]
Can you create a new folder. `cd` to that folder, and use R to create a new site:

```r
blogdown::new_site(theme = "zwbetz-gh/cupper-hugo-theme")
```

You should be able to reproduce this error.

**Comment by zwbetz-gh** [comment]
Pretend I'm a new R user. Walk me through from scratch how I would install the blogdown package, etc.

**Comment by daijiang** [comment]
```r
install.packages("blogdown")
```

If this theme is not for blogdown, why it supports `Rmd` files?

**Comment by zwbetz-gh** [comment]
Nice detective work @yihui
