### ISSUE TITLE
Guidance on what to upstream to you and what not

### ISSUE THREAD

**Issue by danielfdickinson** [zwbetz-gh/cupper-hugo-theme#60]
For lack of a Discussion section for this repo:

I have a modified version of this theme[1] at <https://github.com/danielfdickinson/cupper-hugo-dfd-x>. I would like still be able to upstream things to you that you might be interested in, but as you may recall I also make changes that you are not interested in.

I'd like some guidance on what changes you might want to merge.

So far in the new theme I have made the following changes (besides marking it being different from your theme, with acknowledgments of your theme as the basis of the new theme):

1. On Netlify I disabled Hugo's minification and added the checklinks, html-validator, and minify-html plugins.
   1. checklinks has caught some broken links in the demo pages
   2. html-validator reported a 'whack' of complaints, which I have addressed in my version of the theme. I know not all the warnings are applicable for you, but if you could give me some idea of what fixes from the batch at https://github.com/danielfdickinson/cupper-hugo-dfd-x/pull/5 you'd be interested in, I could upstream those.
2. I have made the theme a module, and by using the environment variable HUGO_MODULE_REPLACEMENTS on Netlify, I am able to do CI against the current version of the theme by deploying exampleSite. I'd be happy to upstream that, if you wish.

I have more changes I'll be merging into the new theme from overrides I made on one of my websites (including the typography you don't need, along with other quirks you probably won't be interested in, but there are updates I think you might want).

[1] It's not a fork in that it's not a GitHub fork, although it is a fork of this project. I do have a GitHub fork as well, to make sending things that are applicable to you as PRs easier.

**Comment by zwbetz-gh** [comment]
Hey @danielfdickinson, 

I can see you put some work into this. 

Though, at the moment, I am not interested in any of the changes.
