### ISSUE TITLE
Emoji color inverts when dark mode is enabled

### ISSUE THREAD

**Issue by Taewan-P** [zwbetz-gh/cupper-hugo-theme#61]
**Describe the bug**

When you have emoji in your article (e.g. 😄🤔🤯), turning on the dark mode will invert the emoji colors

**To Reproduce**
1. Add an emoji in your article
2. Click the dark mode toggle button to enable dark mode

**Expected behavior**

Emoji shouldn't be color inverted. 

**Screenshots**
![light_mode](https://user-images.githubusercontent.com/27392567/132239480-177eb1d1-69b3-4464-bde9-c3893151fa23.png)
![dark_mode](https://user-images.githubusercontent.com/27392567/132239467-97bc71b3-143e-4c23-8b25-675ef60d4a3f.png)

**Desktop (please complete the following information):**
 - OS: Any operating system would occur
 - Browser [e.g. chrome, safari] Same
 - Version [e.g. 22] *

**Smartphone (please complete the following information):**

**Additional context**

This is occurred because markdown translation to html codes will make all the text in paragraph tag inside your article.
The paragraph text colors are changed by dark mode toggle.
The [logic](https://github.com/zwbetz-gh/cupper-hugo-theme/blob/b87a99af1fe064a574ba385a9f11334f4296f314/layouts/partials/head.html#L34) of the toggle is just doing invert using css.

**Comment by Taewan-P** [comment]
I think dark theme should not be made with css invert.

**Comment by zwbetz-gh** [comment]
Hey there.

Will have to investigate how to target emojis with CSS selectors, if it's possible.

**Comment by Taewan-P** [comment]
I fixed this issue by changing the dark theme logic in my [blog](https://chungjungsoo.dev).
```
  <style id="darkTheme">
    .intro-and-nav,
    .main-and-footer {
      background-color: #1c313a;
      color: #fefefe;
    }

    img[src$=".svg"] {
      filter: invert(100%);
      background-color: unset;
    }

    [for="themer"], 
    .pattern [aria-current] {
      background-color: #fefefe !important;
      color: #1c313a !important;
    }

    #menu-button {
      background-color: #fefefe;
      color: #1c313a;
    }

    p code {
      background-color: rgba(228, 224, 220, 0.1) !important;
    }

    * {
      background-color: inherit
    }

  </style>
```
Doesn't look so clean, but you can manually set your dark theme color.

**Comment by zwbetz-gh** [comment]
Hey @Taewan-P,

After doing more investigation, I do not plan to address this issue. 

Glad to hear you've found a solution for your usage of the theme though.
