### ISSUE TITLE
How to change logo

### ISSUE THREAD

**Issue by fcorowe** [zwbetz-gh/cupper-hugo-theme#65]
Hi, first of all, thanks for this great template. We are creating a website for a project and we are struggling to change the logo. We tried by replacing the existing `logo.csv` with an alternative using the same name and format (i.e. `logo.csv`). We did this here: https://github.com/GDSL-SALIENT/salient/tree/main/public/images

Here is the repo to the website: https://github.com/GDSL-SALIENT/salient

How should we change the logo?

Thanks,
Francisco.

**Comment by zwbetz-gh** [comment]
Hi @fcorowe - per the [readme](https://github.com/zwbetz-gh/cupper-hugo-theme#nav-title-or-logo), you will need to put the logo file at `static/images/logo.svg`

You already have a `static` folder in your repo. You just need the `images` sub folder, then place the icon there.

**Comment by zwbetz-gh** [comment]
Also, you mentioned `logo.csv` but that is the incorrect filename. 

It should be `logo.svg`

**Comment by fcorowe** [comment]
Sorry my mistake - I meant `logo.svg` (original post amended). 

And bump! for some reason, I was looking at `/public/images` and dropping the new logo there. 

I have added the image where suggested and it works fine. 

Thanks.
