### ISSUE TITLE
Error when create a new post

### ISSUE THREAD

**Issue by mateusfg7** [zwbetz-gh/cupper-hugo-theme#68]
**Describe the bug**
Hugo show an template error when create a new post.
```
Error: add site dependencies: load resources: loading templates: "/tmp/my-hugo/bug-with-cupper/themes/cupper-hugo-theme/layouts/partials/head.html:14:1": parse failed: template: partials/head.html:14: unclosed action
```

**To Reproduce**
Just run `hugo new posts/my-first-post.md` with clean install of cupper theme and configuration.

**Expected behavior**
Create a new markdown post based on Cupper layout.

**Screenshots**
![image](https://user-images.githubusercontent.com/40613276/148556736-1c4a5bad-f3c6-4943-aba3-e46810cbfa45.png)

**Comment by zwbetz-gh** [comment]
So this is actually not an issue :)

As mentioned in the readme:
https://github.com/zwbetz-gh/cupper-hugo-theme#minimum-hugo-version

You need to install the minimum required hugo version. 

Newer versions of hugo support multi-line templates 👍
