### ISSUE TITLE
xlink:href is deprecated

### ISSUE THREAD

**Issue by jesselawson** [zwbetz-gh/cupper-hugo-theme#71]
[Used here](https://github.com/zwbetz-gh/cupper-hugo-theme/blob/efbc6acf902b3413c1814c3eb662bed0558ca5d1/layouts/partials/nav.html#L19):

```css
        <svg class="bookmark-icon" aria-hidden="true" focusable="false" viewBox="0 0 40 50">
          <use xlink:href="#bookmark"></use>
        </svg>
```

[Deprecation notice](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href)

**Comment by zwbetz-gh** [comment]
Fixed via https://github.com/zwbetz-gh/cupper-hugo-theme/commit/d5ffe2f36953ae9183c3c7e5c6b4bc83ef1961a9
