### ISSUE TITLE
Improve page speed

### ISSUE THREAD

**Issue by stullesha** [zwbetz-gh/cupper-hugo-theme#72]
See tips under opportunities https://web.dev/measure/?url=https%3A%2F%2Fcupper-hugo-theme.netlify.app%2F

**Comment by zwbetz-gh** [comment]
This is not an issue. There is a reason I have issue templates. They should be used. 

Regardless, the demo gets a 98 overall. I’m okay with this. 

![419C78B2-D292-4A6E-AFC5-C47F0D836406](https://user-images.githubusercontent.com/37317628/178104951-3876e463-2e25-4809-834c-1cbbcebbf86b.png)

**Comment by stullesha** [comment]
I cloned it and acted on those issues anyways.
