### ISSUE TITLE
Dropdown menu on a mobile device

### ISSUE THREAD

**Issue by gkabas** [zwbetz-gh/cupper-hugo-theme#73]
**Is your feature request related to a problem? Please describe.**

On a mobile device, the menu on the left becomes an accordion automatically even though there are only two items on the menu. (When I deleted all items, the menu button was still there) 

**Describe the solution you'd like**

It would be great if it is possible to turn this feature off
![Screenshot_20220730-164545_Firefox](https://user-images.githubusercontent.com/46166787/181919609-6df45d66-32b9-43ad-99f5-975d233a5c73.jpg)
.

**Comment by zwbetz-gh** [comment]
The mobile nav menu styles are intentional.

You can [override](https://zwbetz.com/override-a-hugo-theme/) them by commenting out these [styles](https://github.com/zwbetz-gh/cupper-hugo-theme/blob/87e1a8608f44d46f6cc34fc54a4ddadbd2999433/assets/css/template-styles.css#L952-L957).
