### ISSUE TITLE
Large gap appears when I include a collapsible object or an icon

### ISSUE THREAD

**Issue by gkabas** [zwbetz-gh/cupper-hugo-theme#74]
**Describe the bug**
When I add a button or a collapsible, the gap between these items and the line above is large.   

**To Reproduce**
1. Go to to my webpage: https://gkabas.netlify.app/
2. You will see the gap between the titles and "Abstract" is large. I use the following HTML piece (the gap is still there if I use other ways of having a collapsible, such as accordion or expandable):  

**"There is No Planet B", but for Banks There are "Countries B to Z": Domestic Climate Policy and Cross-Border Lending**<br>
with [Emanuela Benincasa](https://emanuelabenincasa.wordpress.com/) and [Steven Ongena](https://sites.google.com/site/stevenongena/), [SSRN](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4075737), [Download](https://gkabas.netlify.app/files/BenincasaKabasOngena.pdf) <details><summary>Abstract: </summary>
We provide evidence that banks increase cross-border lending in response to higher climate policy stringency in their home countries.</details>

A similar gap appears when I include an icon in the text as well.

**Expected behavior**
It may look better if we can reduce this gap. I try to adjust paragraph and line break margins on the CSS file, but it didn't work. 
 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 91.11.0esr (64-bit)

![screenshot](https://user-images.githubusercontent.com/46166787/181920204-123d04c1-ce47-4ab2-8c5f-dc7f3d23b7c1.png)

**Comment by zwbetz-gh** [comment]
The margin you're seeing is intentional.

If you wish, you can [override](https://zwbetz.com/override-a-hugo-theme/) it by changing this [style](https://github.com/zwbetz-gh/cupper-hugo-theme/blob/87e1a8608f44d46f6cc34fc54a4ddadbd2999433/assets/css/template-styles.css#L28-L30).
