### ISSUE TITLE
failed to render shortcode "figureCupper": failed to process shortcode:

### ISSUE THREAD

**Issue by EdwardDeaver** [zwbetz-gh/cupper-hugo-theme#76]
**Describe the bug**
ERROR 2022/08/30 18:23:42 Rebuild failed: : failed to render shortcode "figureCupper": failed to process shortcode: "/layouts/shortcodes/figureCupper.html:14:21": execute of template failed at <$original.Resize>: nil pointer evaluating resource.Resource.Resize

**To Reproduce**
Put file in static/image/something

Make a markdown post in /content/posts/myblogpost.md 
Put in it: 
{{< figureCupper
img="/image/something.png" 
caption="The Moon is an astronomical body that orbits planet Earth and is Earth's only permanent natural satellite. It is the fifth-largest natural satellite in the Solar System, and the largest among planetary satellites relative to the size of the planet that it orbits (its primary). The Moon is after Jupiter's satellite Io the second-densest satellite in the Solar System among those whose densities are known. [Credits](https://images.nasa.gov/details-GSFC_20171208_Archive_e001861.html)." 
command="Resize" 
options="700x" >}}

Note this method below works:
![myimage](/image/something.png)
**Expected behavior**
Image with figure text should appear. 
**Screenshots**

**Desktop (please complete the following information):**
- Mac OS: 12.5
- hugo v0.101.0+extended darwin/arm64 BuildDate=unknown

**Comment by EdwardDeaver** [comment]
btw I really like this theme. Thank you for making it.

**Comment by zwbetz-gh** [comment]
Hi @EdwardDeaver - this shortcode is meant to be used on a [page bundle](https://gohugo.io/content-management/page-bundles/#readout)

So, given your example, restructure your page as follows

Move the markdown file from here:

```
content/posts/myblogpost.md
```

To here:

```
content/posts/myblogpost/index.md
```

Then move the image to:

```
content/posts/myblogpost/image/something.png
```
