### ISSUE TITLE
Superfluous line break in head.html:14

### ISSUE THREAD

**Issue by kubrt-d** [zwbetz-gh/cupper-hugo-theme#78]
Error: add site dependencies: load resources: loading templates: "themes/cupper-hugo-theme/layouts/partials/head.html:14:1": parse failed: template: partials/head.html:14: unclosed action

**Comment by zwbetz-gh** [comment]
This theme requires hugo version 0.81.0 or higher. Make sure you're using that.

This is also documented in the readme: https://github.com/zwbetz-gh/cupper-hugo-theme#minimum-hugo-version
