### ISSUE TITLE
When using headings containing a link, the linked part gets lost

### ISSUE THREAD

**Issue by WetenSchaap** [zwbetz-gh/cupper-hugo-theme#80]
**Describe the bug**

When a heading contains a link, the link is placed at the beginning of the heading, overwriting the rest of the heading.

**To Reproduce**

1. Make a document with headings with links in them:

```
---
title: "Bibliography"
date: 2022-11-28
draft: false
---
## 2nd level heading

### 3rd level heading

### Heading containing a [link](https://gohugo.io/), and acts weird

### Heading containing a [longer link here](https://gohugo.io/), and you see it better
```

2. See error:

![image](https://user-images.githubusercontent.com/36634689/204273481-273f5e50-1d11-4b75-88c8-ab26742c3ce9.png)

**Expected behavior**
Links are simply part of the heading.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Hugo version: v0.107.0
 - Latest `cupper-hugo-theme`

**Comment by zwbetz-gh** [comment]
Hi @WetenSchaap - thanks for reporting this. It's been fixed in https://github.com/zwbetz-gh/cupper-hugo-theme/commit/711a53bfa8925d81097895517ea16d0cc7a8de7c.

**Comment by zwbetz-gh** [comment]
Here's a demo of the fix, for reference: https://cupper-hugo-theme.netlify.app/heading-link-test/
