### ISSUE TITLE
Can I upload png as a logo?

### ISSUE THREAD

**Issue by tamdrashtri** [zwbetz-gh/cupper-hugo-theme#9]
I want the logo of the website to be my profile picture. But when it is converted to svg a lot of details were lost. Is there any way I can change it? Thank you!

**Comment by zwbetz-gh** [comment]
Hi @tamdrashtri. Yes it is possible to use a different image format (although I recommend SVG since it looks nice with dark theme).

Override the template at:
```
layouts/partials/header.html
``` 
and then edit this line:
```
<img src="{{ "images/logo.svg" | absURL }}" alt="">
```

**Comment by tamdrashtri** [comment]
Thank you so much! Also I have trouble updating the date on my blog to the
correct format.

It is messed up and does not show the correct date as well:

https://tamhn.netlify.com/practicing-gratitude/

I appreciate your help! Really need to fix this ASAP.

**Comment by tamdrashtri** [comment]
Fonts on titles: I'm sorry for bugging you, but I also encounter a problem with the font on titles. It works well with English, but for a language I also want to use, Vietnamese, it just breaks and looks awkward. I wonder if I can update the font family too.

**Comment by zwbetz-gh** [comment]
Normally I do one topic per issue, but I will make an exception. 

For your date issue, have you updated the `dateFormat` param in your `config.toml` file?

For your font issue, yes you can change the header font family. To do it, override the file `assets/css/template-styles.css` then change these lines 

```
h1,
h2,
h3,
h4 {
    font-family: Miriam Libre, serif;
    line-height: 1.125;
}
```

**Comment by tamdrashtri** [comment]
I successfully fixed the date issue! Thank you so much.

For the font, I want to change the font family to Merriweather on Google
Fonts. Should I download it on Google Fonts or it will get automatically
updated?

I really appreciate your help!



Vào Th 2, 29 thg 4, 2019 vào lúc 12:38 zwbetz-gh <notifications@github.com>
đã viết:

**Comment by zwbetz-gh** [comment]
You can download the font, or put a link (that google fonts gives you) in the head partial

**Comment by zwbetz-gh** [comment]
Am closing this issue.
